name: Release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npx mix --production
      - name: Git setup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B dist
      - name: Copy .gitignore
        run: |
          cp .gitignore.dist .gitignore
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: 8.0
          version: 2
          args: --profile --ignore-platform-reqs
      - name: Commit built assets
        run: |
          git add -f public/
          git add vendor/*
          git commit -m "Build front-end assets"
          git push -f origin dist
